version: "3"
services:
  postgres:
    image: postgres:latest
#    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "9999:5432"
    environment:
      - POSTGRES_PASSWORD=uep250
      - POSTGRES_USER=s311723
      - POSTGRES_DB=studs
      - POSTGRES_DB_HOST=localhost
      - POSTGRES_DB_PORT=9999
    restart: unless-stopped

  eat-app:
    image: eat-app:latest
#    network_mode: bridge
    container_name: eat-app
    expose:
      - 8080
    ports:
      - "8080:9087"
#    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: